// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXFZopYiGDm0N7_9CA6O1cVg-R8bYN-b8',
    appId: '1:709968087316:web:abcb2beb811fdf992e1a01',
    messagingSenderId: '709968087316',
    projectId: 'smart-shop-622f8',
    authDomain: 'smart-shop-622f8.firebaseapp.com',
    storageBucket: 'smart-shop-622f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA70qK8pdW1wdyKfaRLGxIoORV3hi0ogWc',
    appId: '1:709968087316:android:c17a29275d2339b02e1a01',
    messagingSenderId: '709968087316',
    projectId: 'smart-shop-622f8',
    storageBucket: 'smart-shop-622f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWqZ4QTVRgiifQSa64ZdWaYe_iZDCx6qI',
    appId: '1:709968087316:ios:9e2e7317008d40682e1a01',
    messagingSenderId: '709968087316',
    projectId: 'smart-shop-622f8',
    storageBucket: 'smart-shop-622f8.appspot.com',
    iosBundleId: 'com.example.mlImage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWqZ4QTVRgiifQSa64ZdWaYe_iZDCx6qI',
    appId: '1:709968087316:ios:9e2e7317008d40682e1a01',
    messagingSenderId: '709968087316',
    projectId: 'smart-shop-622f8',
    storageBucket: 'smart-shop-622f8.appspot.com',
    iosBundleId: 'com.example.mlImage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXFZopYiGDm0N7_9CA6O1cVg-R8bYN-b8',
    appId: '1:709968087316:web:725808458e88f1c32e1a01',
    messagingSenderId: '709968087316',
    projectId: 'smart-shop-622f8',
    authDomain: 'smart-shop-622f8.firebaseapp.com',
    storageBucket: 'smart-shop-622f8.appspot.com',
  );
}
